// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'hyphenate', kind: "module", path: './hyphenate.html', attributes: []},
{name: 'hyphenate.BitArray', kind: "structdeclaration", path: './hyphenate/BitArray.html', attributes: []},
{name: 'hyphenate.BitArray.empty', kind: "functiondeclaration", path: './hyphenate/BitArray.empty.html', attributes: ["property", "const"]},
{name: 'hyphenate.BitArray.front', kind: "functiondeclaration", path: './hyphenate/BitArray.front.html', attributes: ["property", "const"]},
{name: 'hyphenate.BitArray.popFront', kind: "functiondeclaration", path: './hyphenate/BitArray.popFront.html', attributes: []},
{name: 'hyphenate.BitArray.this', kind: "functiondeclaration", path: './hyphenate/BitArray.this.html', attributes: []},
{name: 'hyphenate.Hyphenator', kind: "structdeclaration", path: './hyphenate/Hyphenator.html', attributes: []},
{name: 'hyphenate.Hyphenator.hyphenate', kind: "functiondeclaration", path: './hyphenate/Hyphenator.hyphenate.html', attributes: ["const"]},
{name: 'hyphenate.Hyphenator.this', kind: "functiondeclaration", path: './hyphenate/Hyphenator.this.html', attributes: []},
];
